test github action with config server ui

diff --git a/.github/workflows/agent_test.yml b/.github/workflows/agent_test.yml
--- a/.github/workflows/agent_test.yml
+++ b/.github/workflows/agent_test.yml
@@ -106,6 +106,8 @@ jobs:
       # the action has not been updated a while, but it always uses the latest plugin version
       - name: Run DependencyCheck plugin
         uses: dependency-check/Dependency-Check_Action@main
+        id: depcheck
+        continue-on-error: true
         with:
           project: inspectIT/inspectit-ocelot-agent
           path: 'inspectit-ocelot-agent'
@@ -121,6 +123,12 @@ jobs:
         with:
           name: dependency-check-report-ocelot-agent
           path: ${{ github.workspace }}/reports
+      # if DependencyCheck failed, the job should also fail, but only after the results were uploaded
+      - name: Validate DependencyCheck outcome
+        if: ${{ steps.depcheck.outcome == 'failure' }}
+        run: |
+          echo "DependencyCheck failed"
+          exit 1
 
   jmh-compile:
     name: 'Compile JMH Tests'
diff --git a/.github/workflows/configuration_ui_test.yml b/.github/workflows/configuration_ui_test.yml
--- a/.github/workflows/configuration_ui_test.yml
+++ b/.github/workflows/configuration_ui_test.yml
@@ -25,13 +25,35 @@ jobs:
   dependency-scan:
     name: Dependency Scan
     runs-on: ubuntu-latest
-    env:
-      working-directory: ./components/inspectit-ocelot-configurationserver-ui
     container: eclipse-temurin:17
     steps:
       - uses: actions/checkout@v3
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Scan dependencies
-        working-directory: ${{env.working-directory}}
-        run: ../../gradlew :inspectit-ocelot-configurationserver-ui:dependencyCheckAnalyze
+      - name: build
+        run: ./gradlew :inspectit-ocelot-configurationserver-ui:buildFrontend
+      - name: Run DependencyCheck plugin
+        uses: dependency-check/Dependency-Check_Action@main
+        id: depcheck
+        continue-on-error: true
+        with:
+          project: inspectIT/inspectit-ocelot-configuration-server-ui
+          path: 'components/inspectit-ocelot-configurationserver-ui'
+          format: 'HTML'
+          out: 'reports'
+          args: >
+            --disableAssembly
+            --disableNodeAudit
+            --nvdApiKey ${{ secrets.NVD_API_KEY }}
+            --nvdApiDelay 10000
+      - name: Upload test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: dependency-check-report-ocelot-configurationserver-ui
+          path: ${{ github.workspace }}/reports
+      # if DependencyCheck failed, the job should also fail, but only after the results were uploaded
+      - name: Validate DependencyCheck outcome
+        if: ${{ steps.depcheck.outcome == 'failure' }}
+        run: |
+          echo "DependencyCheck failed"
+          exit 1
diff --git a/.github/workflows/configurationserver_test.yml b/.github/workflows/configurationserver_test.yml
--- a/.github/workflows/configurationserver_test.yml
+++ b/.github/workflows/configurationserver_test.yml
@@ -41,12 +41,14 @@ jobs:
       - uses: actions/checkout@v3
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Build Configuration-Server
-        run: ./gradlew :inspectit-ocelot-configurationserver:assemble
+      - name: build
+        run: ./gradlew :inspectit-ocelot-configurationserver:bootJarWithFrontend
       - name: Run DependencyCheck plugin
         uses: dependency-check/Dependency-Check_Action@main
+        id: depcheck
+        continue-on-error: true
         with:
-          project: inspectIT/inspectit-ocelot-configurationServer
+          project: inspectIT/inspectit-ocelot-configuration-server
           path: 'components/inspectit-ocelot-configurationserver'
           format: 'HTML'
           out: 'reports'
@@ -58,5 +60,11 @@ jobs:
       - name: Upload test results
         uses: actions/upload-artifact@v4
         with:
-          name: dependency-check-report-ocelot-agent
+          name: dependency-check-report-ocelot-configurationserver
           path: ${{ github.workspace }}/reports
+      # if DependencyCheck failed, the job should also fail, but only after the results were uploaded
+      - name: Validate DependencyCheck outcome
+        if: ${{ steps.depcheck.outcome == 'failure' }}
+        run: |
+          echo "DependencyCheck failed"
+          exit 1
