add security cron job (#1677)
* merge dependabot

* update DependencyCheck

* test github action with agent

* change project

* change config 1

* change config 2

* change config 3

* test github action with config server

* test github action with config server ui

* remove build from depcheck

* test github action with configdocsgenerator

* remove unnecessary property

* use action in release

* add cron jobs

* reinclude build to depcheck

* try including configdocsgenerator

* try including configdocsgenerator 2

* try including configdocsgenerator 3

* try including configdocsgenerator 4

* try including configdocsgenerator 5

* try including configdocsgenerator 6

* try including configdocsgenerator 7

* try including configdocsgenerator 8

* try including configdocsgenerator 9

* included configsdocsgenerator and UI

* refactor config-server workflow

diff --git a/.github/workflows/configurationserver_test.yml b/.github/workflows/configurationserver_test.yml
--- a/.github/workflows/configurationserver_test.yml
+++ b/.github/workflows/configurationserver_test.yml
@@ -36,13 +36,35 @@ jobs:
   dependency-scan:
     name: Dependency Scan
     runs-on: ubuntu-latest
-    env:
-      working-directory: ./components/inspectit-ocelot-configurationserver
     container: eclipse-temurin:17
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-      - name: Scan dependencies
-        working-directory: ${{env.working-directory}}
-        run: ../../gradlew :inspectit-ocelot-configurationserver:dependencyCheckAnalyze
+      - name: build Configuration-Server
+        run: ./gradlew :inspectit-ocelot-configurationserver:bootJarWithFrontend
+      - name: Run DependencyCheck
+        uses: dependency-check/Dependency-Check_Action@main
+        id: depcheck
+        continue-on-error: true
+        with:
+          project: inspectIT/inspectit-ocelot-configuration-server
+          path: 'components/inspectit-ocelot-configurationserver'
+          format: 'HTML'
+          out: 'reports/configuration-server'
+          args: >
+            --disableAssembly
+            --disableNodeAudit
+            --nvdApiKey ${{ secrets.NVD_API_KEY }}
+            --nvdApiDelay 10000
+      - name: Upload test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: dependency-check-report-ocelot-configurationserver
+          path: ${{ github.workspace }}/reports
+      # if DependencyCheck failed, the job should also fail, but only after the results were uploaded
+      - name: Validate DependencyCheck outcome
+        if: ${{ steps.depcheck.outcome == 'failure' }}
+        run: |
+          echo "DependencyCheck failed"
+          exit 1
